### ISSUE TITLE
Returning a list of partner-id values the device is would be helpful

### ISSUE THREAD

**Issue by schmidtw** [Comcast/codex-gungnir#69]
In the response to `/device/{DeviceId}/status` it would be very helpful to get the list of partner-id values the device has most recently used to connect to Xmidt.

```json
{

    "deviceid": "5",
    "last_offline_reason": "ping miss",
    "now": "2019-02-26T20:18:15.188881748Z",
    "since": "2019-02-26T20:18:15.188881748Z",
    "state": "online",
    "partner-ids": [
        "hello",
        "world" ]
}
```

**Comment by kristinaspring** [comment]
added partner IDs, but set it as `partner_ids` in the json being returned.  This matches the json key value that is found in the wrp message.
